---
# un playbook est tableau de plays

- hosts: all
  tasks: 
    - name: Update Openssh !
      apt:
        name: openssh-server
        state: latest
        update_cache: yes

- hosts: app
  tasks:
    - name: Update Apache !
      apt:
        name: apache2
        state: latest
        update_cache: yes


- hosts: bdd
  tasks:
    - name: Update Maria-db !
      apt:
        name: mariadb-server
        state: latest
        update_cache: yes

